### ISSUE TITLE
Update Platform Integration Package

### ISSUE THREAD

**Issue by sid-at-jauntin** [jauntin/pdf-platform-sdk#1]
## Description

This project should be updated with easier-to-use data objects for requests and responses.

The update should be a new version because the current version is being used by the demo app. The demo app can also be updated to work with this version when possible.

## Acceptance Criteria

- [ ] Use data objects for Requests and Responses
- [ ] The updated version is published as V2

## Tasks

- [ ] Update the project to use data objects

## Definition of Ready

- [x] Doesn't have unmet dependencies
- [x] Description is clear and concise
- [x] Business value is clear
- [x] Has tasks that make it estimable
- [x] Small enough to be doable in 2 days max
- [x] Acceptance criteria is provided and clear
